# Generated by Django 6.1 on 2026-09-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='display_name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='display_npm',
            new_name='npm',
        ),
    ]
