# Generated by Django 6.1 on 2026-09-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_rename_display_name_mahasiswa_nama_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
