# Generated by Django 6.1 on 2026-09-13 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=8)),
                ('study_program', models.CharField(blank=True, max_length=64)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
    ]
