# Generated by Django 6.1 on 2026-09-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.CharField(max_length=16),
        ),
    ]
