# Generated by Django 6.0.6 on 2026-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_starred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
    ]
